-- Các bảng contacts, promotions và cột khuyến mãi của orders đã được gộp vào file chính:
-- ban_banh-3.sql (ở thư mục gốc project)
--
-- Trong ban_banh-3.sql có:
-- - Bảng contacts (form liên hệ)
-- - Bảng promotions (mã khuyến mãi)
-- - Bảng orders có thêm cột promo_code, discount_amount
-- - Dữ liệu mẫu mã khuyến mãi (SINHNHAT15, FREESHIP350, SWEET10)
--
-- Chạy file ban_banh-3.sql trong phpMyAdmin/MySQL để tạo đầy đủ database.
